# config.toml voor Hugo met thema Ananke

baseURL = "https://example.com/"   # tijdelijke placeholder, later vervangen door Netlify domein
languageCode = "nl-nl"
title = "Mijn Hugo Blog"
theme = "ananke"
paginate = 5

# Metadata voor de site
[params]
  author = "Jouw Naam"
  description = "Een persoonlijke blog gemaakt met Hugo en Netlify"

# Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

# Build settings voor Netlify (optioneel)
[build]
  publishDir = "public"
